openapi: 3.0.0
info:
  title: ClaimsStatus.v1
  version: '1.0'
  description: Claims Status
  contact:
    name: Medibank API Support
    email: apisupport@medibank.com.au
    url: 'https://attraintegration.stoplight.io'
  license:
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    name: Apache 2.0
  termsOfService: 'https://www.medibank.com.au/terms-and-conditions/'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/claim:
    get:
      summary: Fetch claims
      tags:
        - Claims
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../policies/PolicyDetails.v1.yaml
              examples:
                PolicyDetails:
                  value:
                    - policyId: 1
                      policyName: Health
                      Product:
                        productId: 1
                        productName: Credit Card
                        productDescription: This is for credit card
                      Preference:
                        id: '123'
                        details: Its user preference
                      Address:
                        addressId: 1
                        address1: Electronic
                        street: city
                        city: Bangalore
                        state: KA
                        country: IND
                        zip: '560000'
                        Contact:
                          mobile: 9999999999
                          emailId: Messi@gmail.com
                          phoneNumber: 9999999999
                    - policyId: 2
                      policyName: Health
                      Product:
                        productId: 1
                        productName: Credit Card
                        productDescription: This is for credit card
                      Preference:
                        id: '123'
                        details: Its user preference
                      Address:
                        addressId: 1
                        address1: Electronic
                        street: city
                        city: Bangalore
                        state: KA
                        country: IND
                        zip: '560000'
                        Contact:
                          mobile: 9999999999
                          emailId: Messi@gmail.com
                          phoneNumber: 9999999999
                    - policyId: 3
                      policyName: Health
                      Product:
                        productId: 1
                        productName: Credit Card
                        productDescription: This is for credit card
                      Preference:
                        id: '123'
                        details: Its user preference
                      Address:
                        addressId: 1
                        address1: Electronic
                        street: city
                        city: Bangalore
                        state: KA
                        country: IND
                        zip: '560000'
                        Contact:
                          mobile: 9999999999
                          emailId: Messi@gmail.com
                          phoneNumber: 9999999999
                Policy Details schema:
                  value:
                    - policyId: 0
                      policyName: string
                      Product:
                        productId: 0
                        productName: string
                        productDescription: string
                      Preference:
                        id: string
                        details: string
                      Address:
                        addressId: 0
                        address1: string
                        street: string
                        city: string
                        state: string
                        country: string
                        zip: string
                        Contact:
                          mobile: 9999999999
                          emailId: string
                          phoneNumber: 0
                PolicyDetails1:
                  value:
                    - policyId: 1
                      policyName: Health
                      Product:
                        productId: 1
                        productName: Credit Card
                        productDescription: This is for credit card
                      Preference:
                        id: '123'
                        details: Its user preference
                      Address:
                        addressId: 1
                        address1: Electronic
                        street: city
                        city: Bangalore
                        state: KA
                        country: IND
                        zip: '560000'
                        Contact:
                          mobile: 9999999999
                          emailId: Messi@gmail.com
                          phoneNumber: 9999999999
      operationId: get-api-claim
      description: |-
        <span style="font-size: 1.5em; color: #5D535E;">
          <i class="fas fa-robot fa-xs"></i> Get/Fetch claims
        </span>

        Returns a list of claims for Claims.If specific claims are desired, users can specify the `'claimId'` or multiple thereof values in the header.

        More information about required parameters and authentication can be seen below.

        ```bash

        curl --request GET \
          --url https://medibankdemo.stoplight.io:5555/api/claim
        ```
components:
  schemas: {}
tags:
  - name: Claims
